version: '3.8'

services:
  api:
    build: .
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # Docker will pull MONGO_URI and VERIFY_TOKEN straight from your .env file automatically
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=redis://redis:6379
      - VERIFY_TOKEN=${VERIFY_TOKEN}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis  # <-- Notice 'mongo' is gone from here!

  redis:
    image: redis:7.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: